services:
  - type: web
    name: laravel-app
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan migrate --force
      npm install
      npm run build
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    rootDir: . # use "backend" if Laravel is inside a subfolder
    publicDir: public
